backend/modules/tr/controllers/HelperController.php
<?php

namespace backend\modules\tr\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;

use common\components\CommonHelper;
use common\components\TimeReportHelper;

use common\models\cl\Client;
use common\models\hr\Employee;
use common\models\tr\JobBudgeting;
use common\models\tr\JobBudgetingTemp;

class HelperController extends Controller
{
  public $layout;
  public function actions()
  {
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ],
    ];
  }
  /*start rapih*/

  public function actionSrcemployejob($q = null, $id = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];

    $data = JobBudgeting::find()->where("job_id = '{$id}' AND employee_id LIKE '%{$q}%'")->all();
    if (!empty($data)) {
      $out['results'] = array();
      foreach ($data as $key => $d) {
        $arr = array(
          'id' => $d['employee_id'],
          'text' => $d['employee_id'] . ' - ' . $d['employee']['full_name'] . ' - ' . $d['employee']['level']['level_name'],
        );
        array_push($out['results'], $arr);
      }
    }
    return $out;
  }

  public function actionSrcemployejobtemp2($q = null, $id = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];

    $data = JobBudgetingTemp::find()->where("job_id = '{$id}' AND employee_id LIKE '%{$q}%'")->all();
    if (!empty($data)) {
      $out['results'] = array();
      foreach ($data as $key => $d) {
        $arr = array(
          'id' => $d['employee_id'],
          'text' => $d['employee_id'] . ' - ' . $d['employee']['full_name'] . ' - ' . $d['employee']['level']['level_name'],
        );
        array_push($out['results'], $arr);
      }
    }
    return $out;
  }

  public function actionSrcclient($q = null, $id = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];

    $data = Client::find()->where("id = '{$q}' or client_name LIKE '%{$q}%'")->asArray()->all();
    if (!empty($data)) {
      $out['results'] = array();
      foreach ($data as $key => $d) {
        $arr = array(
          'id' => $d['id'],
          'text' => $d['client_code'] . ' - ' . $d['client_name'],
        );
        array_push($out['results'], $arr);
      }
    }
    return $out;
  }


  /*end rapih*/




  public function actionSrcclientopt($q = null, $id = null)
  {
    //SrcSupplierOpt
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];
    if (!is_null($q)) {
      $model = Client::find()
        ->select('Id as id, Name as text, OfficeCP, OfficePhone, OfficeFax, OfficeAddress')
        ->where(
          "OfficeCP LIKE '%{$q}%' OR Name LIKE '%{$q}%' OR Id = '{$q}' "
        )
        ->limit(10)
        ->asArray()
        ->all();
      $out['results'] = array();
      foreach ($model as $data) {
        $name = $data['text'];
        $cp = $data['OfficeCP'];
        $phone = $data['OfficePhone'];
        $fax = $data['OfficeFax'];
        $address = $data['OfficeAddress'];

        $array = array(
          'id' => $data['id'],
          'text' => $data['id'] . ' - ' . $name,
        );
        array_push($out['results'], $array);
      }
    } elseif ($id > 0) {
      $out['results'] = ['id' => $id, 'text' => Client::findOne($id)->Name];
    }

    return $out;
  }

  // kamal 21 Mar 2021
  public function actionSearchGroup($entity_name = null, $division_name = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
  }

  public function actionSrcemployeeopt($q = null, $id = null, $entity = null, $division = null, $grup = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];
    if (!is_null($q)) {
      if ($entity != null or $division != null) {
        if ($grup != null) {
          $model = Employee::find()

            ->where(
              "(parent_id = '{$grup}') AND (full_name LIKE '%{$q}%' OR user_id LIKE '%{$q}%')"
            )
            ->all();
        } else {
          $model = Employee::find()
            ->where(
              "(entity_id ='{$entity}' OR div_id = '{$division}') AND (full_name LIKE '%{$q}%' OR user_id LIKE '%{$q}%')"
            )
            ->all();
        }
      } elseif ($grup != null) {
        $model = Employee::find()
          ->joinwith('level')
          ->where(
            "(parent_id = '{$grup}') AND (hr_employee.full_name LIKE '%{$q}%' OR hr_employee.user_id LIKE '%{$q}%' OR cm_level.level_name LIKE '{$q}')"
          )
          ->all();
      } elseif ($entity == null and $division == null and $grup == null) {
        $model = Employee::find()
          ->joinwith('level')
          ->where(
            "hr_employee.full_name LIKE '%{$q}%' OR hr_employee.user_id LIKE '%{$q}%' OR cm_level.level_name LIKE '{$q}'"
          )
          ->all();
      }
      // $model = Employee::find()
      //     ->select('Id as id, fullName as text, entityId')
      //     ->where(
      //       "entityId ='{$entity}' OR divisionID = '{$division}' OR parentID ='{$grup}' AND fullName LIKE '%{$q}%' OR Id = '{$q}'"
      //     )
      //     ->limit(10)
      //     ->asArray()
      //     ->all();
      $out['results'] = array();
      foreach ($model as $key => $data) {
        // $fullName = $data['text'];
        $array = array(
          'id' => $data['user_id'],
          'text' => $data['user_id'] . ' - ' . $data['full_name'] . ' - ' . $data['level']['level_name'],
        );
        array_push($out['results'], $array);
      }
    } elseif ($grup != null) {
      if ($grup != null) {
        $model = Employee::find()
          ->where(
            "parent_id = '{$grup}'  AND full_name LIKE '%{$q}%' OR user_id = '{$q}'"
          )

          ->all();
      }

      // $model = Employee::find()
      //     ->select('Id as id, fullName as text, entityId')
      //     ->where(
      //       "entityId ='{$entity}' OR divisionID = '{$division}' OR parentID ='{$grup}' AND fullName LIKE '%{$q}%' OR Id = '{$q}'"
      //     )
      //     ->limit(10)
      //     ->asArray()
      //     ->all();
      $out['results'] = array();
      foreach ($model as $key => $data) {
        // $fullName = $data['text'];
        $array = array(
          'id' => $data['user_id'],
          'text' => $data['user_id'] . ' - ' . $data['full_name'] . ' - ' . $data['level']['level_name'],
        );
        array_push($out['results'], $array);
      }
    } elseif ($id > 0) {
      $data = Employee::findOne($id);
      $out['results'] = ['id' => $id, 'text' => $data->user_id . ' - ' . $data->full_name];
    }
    return $out;
  }


  public function actionSrcemployemanager($q = null, $JobID = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];
    if (!is_null($q)) {
      // $model = JobBudgeting::find()
      // ->where(
      //   "JobID = '{$JobID}' AND EmployeeID LIKE '%{$q}%'"
      //   )
      //   // ->limit(10)
      //   // ->asArray()
      //   ->all();

      $model = Employee::find()
        ->where(
          "full_name LIKE '%{$q}%'"
        )
        ->all();

      $out['results'] = array();
      foreach ($model as $key => $data) {
        // $out['results'] = ['id' => $data->EmployeeID, 'text' => $data->EmployeeID.' - '.$data->employee->fullName];
        // $fullName = $data['text'];
        // print_r($data['employee']['fullName']);
        $array = array(
          'id' => $data['user_id'],
          'text' => $data['user_id'] . ' - ' . $data['full_name'] . ' - ' . $data['level']['level_name'],
        );
        array_push($out['results'], $array);
      }
    } elseif (is_null($q)) {
      // $model = JobBudgeting::find()
      // ->where(
      //   "JobID = '{$JobID}' AND EmployeeID LIKE '%{$q}%'"
      //   )
      //   // ->limit(10)
      //   // ->asArray()
      //   ->all();

      $model = Employee::find()
        ->where(
          "full_name LIKE '%{$q}%'"
        )
        ->all();

      $out['results'] = array();
      foreach ($model as $key => $data) {
        // $out['results'] = ['id' => $data->EmployeeID, 'text' => $data->EmployeeID.' - '.$data->employee->fullName];
        // $fullName = $data['text'];
        // print_r($data['employee']['fullName']);
        $array = array(
          'id' => $data['user_id'],
          'text' => $data['user_id'] . ' - ' . $data['full_name'] . ' - ' . $data['level']['level_name'],
        );
        array_push($out['results'], $array);
      }
    } elseif ($id > 0) {
      $data = JobBudgeting::findOne($id);
      $out['results'] = ['id' => $id, 'text' => $data->job_id . ' - ' . $data->employee->full_name . ' - ' . $data->employee->level->level_name];
    }
    return $out;
  }

  public function actionSrcemployejobtemp($q = null, $JobID = null)
  {
    \Yii::$app->response->format = Response::FORMAT_JSON;
    $out = ['results' => ['id' => '', 'text' => '']];
    if (!is_null($q)) {
      // $model = JobBudgeting::find()
      // ->where(
      //   "JobID = '{$JobID}' AND EmployeeID LIKE '%{$q}%'"
      //   )
      //   // ->limit(10)
      //   // ->asArray()
      //   ->all();

      $model = JobBudgetingTemp::find()
        ->where(
          "job_id = '{$JobID}' AND employee_id LIKE '%{$q}%'"
        )
        ->all();

      $out['results'] = array();
      foreach ($model as $key => $data) {
        // $out['results'] = ['id' => $data->EmployeeID, 'text' => $data->EmployeeID.' - '.$data->employee->fullName];
        // $fullName = $data['text'];
        // print_r($data['employee']['fullName']);
        $array = array(
          'id' => $data['employee_id'],
          'text' => $data['employee_id'] . ' - ' . $data['employee']['full_name'] . ' - ' . $data['employee']['level']['level_name'],
        );

backend/modules/tr/controllers/JobcreateController.php
<?php

namespace backend\modules\tr\controllers;

use Yii;
use yii\base\Exception;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use common\components\CommonHelper;
use common\components\HelperDB;
use common\components\TimeReportHelper;

use common\models\tr\Job;
use common\models\tr\search\JobSearch;


class JobcreateController extends Controller
{
  protected function findModel($id)
  {
    if (($model = Job::findOne($id)) !== null) {
      return $model;
    }

    throw new NotFoundHttpException('The requested page does not exist.');
  }

  public function behaviors()
  {
    return [
      'verbs' => [
        'class' => VerbFilter::className(),
        'actions' => [
          'delete' => ['POST'],
        ],
      ],
    ];
  }
  public function actionIndex()
  {
    $searchModel = new JobSearch();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

    return $this->render('index', [
      'searchModel' => $searchModel,
      'dataProvider' => $dataProvider,
    ]);
  }

  public function getDataForForm($model)
  {
    $data = array();

    $data['Division'] = TimeReportHelper::getDivision();
    $data['Entity'] = TimeReportHelper::getEntity();
    $data['Client'] = TimeReportHelper::getClient();
    $data['Employee'] = TimeReportHelper::getEmployee();
    $data['VempGroup'] = TimeReportHelper::getVempGroup();
    return $data;
  }

  public function actionN($id = '')
  {

    $modelJob = empty($id) ? new Job() : $this->findModel($id);
    $modelJob->scenario = 'create';

    // $abc = $this->getDataForForm($modelJob);
    // var_dump('coba');
    // die();
    return $this->renderAjax('n', [
      'id' => $id,
      'data' => $this->getDataForForm($modelJob),
      'modelJob' => $modelJob,
    ]);
  }
  public function actionN_code($id = '')
  {
    // var_dump('coba');
    // die();

    $modelJob = empty($id) ? new Job() : $this->findModel($id);
    $modelJob->scenario = 'update_code';

    return $this->renderAjax('n_code', [
      'id' => $id,
      'data' => $this->getDataForForm($modelJob),
      'modelJob' => $modelJob,
    ]);
  }

  public function actionSave($id = null)
  {
    $user = CommonHelper::getUserIndentity();
    $post = Yii::$app->request->post();
    $modelJob = empty($id) ? new Job() : $this->findModel($id);
    $modelJob->scenario = 'create';

    $result = [
      'model' => [],
      'state' => [
        'status' => false,
        'message' => 'Error : default'
      ]
    ];

    $job_id = null;
    $transaction = \Yii::$app->db->beginTransaction();
    if ($modelJob->load($post)) {
      if ($modelJob->validate()) {
        try {
          if ($modelJob->isNewRecord) {
            $modelJob->job_status = 0;
            $modelJob->flag = 0;
            $modelJob->created_by = $user->user_id;

            // $sql = "call command_sql('new-job-manager','" . $modelJob->id . ";" . $modelJob->manager_id . ";" . $user->user_id . "');";
            // $sql = "call cud_data('insert-job-manager','" . $modelJob->JobID . ";" . $modelJob->Manager . ";" . $user->Id . "')";
          } else {
            $modelJob_old = $this->findModel($id);

            $modelJob->updated_by = $user->user_id;

            // $sql = "call command_sql('new-job-manager','" . $modelJob->id . ";" . $modelJob_old->manager_id . ";" . $modelJob->manager_id . ";" . $user->user_id . "')";
            // $sql = "call cud_data('insert-job-manager','" . $modelJob->JobID . ";" . $modelJob_old->Manager . ";" . $modelJob->Manager . ";" . $user->Id . "')";
            $job_id = $modelJob->id;
          }
          // var_dump('$sql');
          // die();
          $modelJob->job_fee = CommonHelper::ResetDecimal($modelJob->job_fee);
          // $modelJob->Fee = CommonHelper::ResetDecimal($modelJob->Fee);

          // Yii::$app->db->createCommand($sql)->queryOne();
          $result = HelperDB::save($modelJob);
          if (is_null($job_id)) {
            $sql = "call command_sql('new-job-manager','" . $modelJob->id . ";;" . $modelJob->manager_id . ";" . $user->user_id . "')";
          } else {
            $sql = "call command_sql('new-job-manager','" . $modelJob->id . ";" . $modelJob_old->manager_id . ";" . $modelJob->manager_id . ";" . $user->user_id . "')";
          }
          Yii::$app->db->createCommand($sql)->queryOne();


          if ($result['state']['status'] == true) {
            // $mail = $modelJob->manager->email;
            $mail = $modelJob->manager->user_email;
            if (!empty($mail)) {
              $send_email = $this->Email($mail, 'THERE IS A NEW DRAFT JOB', $modelJob);
              // $send_email = true;
              if ($send_email) {
                $result['state']['status'] = true;
                $result['state']['message'] = "Success";
                $transaction->commit();
              } else {
                $result['state']['status'] = false;
                $result['state']['message'] = "Can't Send Email, please cek email address " . $mail;
                $transaction->rollback();
              }
            } else {
              $result['state']['status'] = false;
              $result['state']['message'] = "Can't Send Email, Manager's email is empty";
            }
          }
        } catch (Exception $e) {
          $result['state']['status'] = false;
          $result['state']['message'] = HelperDB::db_trigger_error($e->getMessage());
          $transaction->rollBack();
        }
      }
    }

    return json_encode($result['state']);
  }

  public function actionDelete($id)
  {
    try {
      $sql = "call command_sql('delete-all-job-detail'," . $id . ");";
      Yii::$app->db->createCommand($sql)->queryOne();

      $modelJob = $this->findModel($id);
      $modelJob->delete();
      return $this->redirect(['index']);
    } catch (\Exception $e) {
      return CommonHelper::db_trigger_error($e->getMessage());
    }
  }

  protected function Email($sendto, $subject, $modelJob, $status = "", $layouts = 'layouts/JobCreate')
  {
    Yii::$app->cache->flush();

    $from = Yii::$app->params['appNotificationEmail'];
    $cc = Yii::$app->params['appNotificationEmailCC'];

    $to = array();
    $to[$sendto] = $sendto;

    if (!empty($to)) {
      $to = $to;
      $html = ['html' => $layouts];
      $html_bind = ['title' => $subject, 'modelJob' => $modelJob, 'status' => $status];

      $compose = Yii::$app->mailer->compose($html, $html_bind);
      $compose->setFrom($from);
      $compose->setTo($to);
      if (!empty($cc)) {
        $compose->setCc($cc);
      }
      $compose->setSubject($subject);

      if ($compose->send()) {
        return "true";
      } else {
        return "false";
      }
    }
  }
}

backend/modules/tr/views/jobcreate/n.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;

use kartik\widgets\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\widgets\SwitchInput;
use yii\widgets\MaskedInput;

use common\components\JobHelper;
use common\models\hr\Employee;

JobHelper::set_title_txt($this, ['label' => Yii::t('backend', 'JOB LIST'), 'url' => ['all']], ($modelJob->isNewRecord) ? 'Create New Job' : 'Update Job  : ' . $modelJob->job_code);
echo JobHelper::widget_pjax('DetailModal');
$form = ActiveForm::begin(JobHelper::begin_form('job-form'));
echo $form->errorSummary($modelJob);
\yii\widgets\Pjax::begin(['id' => rand() . 'pjax', 'enablePushState' => false, 'id' => 'job-pjax']);
?>
<div class="alert alert-danger" id="error" style="display:none"></div>

<b>Client</b>
<div class="form-group-attached mb-3">
	<div class="row">
		<div class="col-md-8">
			<?= $form->field($modelJob, 'id', ['options' => ['class' => '']])->hiddenInput(['id' => 'id'])->label(false); ?>

			<?php
			echo $form->field($modelJob, 'client_id', ['options' => ['onchange' => 'lateJob()', 'class' => ' form-group form-group-default form-group-default-select2 client-select']])->widget(
				Select2::classname(),
				[
					'data' =>  $data['Client'],
					'options' => ['id' => 'Class', 'placeholder' => 'Select ...', 'class' => 'readonly'],

				]
			);
			?>
		</div>
		<div class="col-md-4">
			<?php
			echo $form->field($modelJob, 'job_code', ['options' => ['class' => ' form-group form-group-default']])->textInput(['class' => "form-control"]);
			?>
		</div>
	</div>
</div>
<b>Job Description</b>
<div class="form-group-attached mb-3">

	<div class="row">
		<div class="col-md-2">
			<?=
			$form->field(
				$modelJob,
				'start_date',
				[
					'template' => '{label}{input}', 'options' => ['class' => 'form-group form-group-default input-group'],
				]
			)->widget(DatePicker::classname(), [
				'type' => DatePicker::TYPE_INPUT,
				'value' => date('Y-m-d'),
				'pluginOptions' => [
					'autoclose' => true,
					'format' => 'yyyy-mm-dd',
				],
			])
			?>
		</div>
		<div class="col-md-2">
			<?=
			$form->field(
				$modelJob,
				'end_date',
				[
					'template' => '{label}{input}', 'options' => ['class' => 'form-group form-group-default input-group'],
				]
			)->widget(DatePicker::classname(), [
				'type' => DatePicker::TYPE_INPUT,
				'value' => date('Y-m-d'),
				'pluginOptions' => [
					'autoclose' => true,
					'format' => 'yyyy-mm-dd',
				],
			])
			?>
		</div>
		<div class="col-md-8">
			<?php
			echo $form->field($modelJob, 'description')->textInput();
			?>
		</div>

	</div>
</div>
<b>Manager & Fee</b>
<div class="form-group-attached mb-3">
	<div class="row">

		<div class="col-md-4">

			<?php
			$Manager = '';

			if (!$modelJob->isNewrecord || !empty($modelJob->manager_id)) {
				$dataManager = Employee::findOne($modelJob->manager_id);
				$Manager = empty($dataManager->full_name) ? $modelJob->manager_id : $dataManager->user_id . ' - ' . $dataManager->full_name . ' - ' . $dataManager->level->level_name;
			}
			echo $form->field($modelJob, 'manager_id', ['options' => ['class' => ' form-group form-group-default form-group-default-select2']])
				->widget(Select2::classname(), [
					'initValueText' => $Manager,
					'options' => ['placeholder' => 'Search Manager ... '],
					'pluginOptions' => [
						'minimumInputLength' => 2,
						'tags' => false,
						'ajax' => [
							'url' => Url::to(['helper/srcemployemanager', 'id' => $modelJob->id]),
							'dataType' => 'json',
							'data' => new JsExpression('function(params) { return {q:params.term , JobID:$("#JobID").val()}; }'),
						],
					],
				]);
			?>
		</div>
		<div class="col-md-4">
			<?=
			$form->field($modelJob, 'job_fee')->widget(MaskedInput::className(), [
				'clientOptions' => [
					'alias' => 'decimal',
					'groupSeparator' => ',',
					'autoGroup' => true,
				],
			]);
			?>
		</div>

		<div class="col-md-4">
			<?php
			echo $form->field(
				$modelJob,
				'include_ope',
				['options' => ['class' => ' form-group form-group-default']]
			)->widget(
				SwitchInput::className(),
				['pluginOptions' => [
					'size' => 'small',
					'onText' => 'Yes',
					'offText' => 'No',
				]]
			);

			?>
		</div>
	</div>
</div>

<?php
echo '<button type="button" class="btn btn-info btn-lg float-right" data-dismiss="modal">CANCEL</button>';
echo Html::submitButton('SAVE', ['class' => 'btn btn-success btn-lg float-right']);
?>

<?php \yii\widgets\Pjax::end(); ?>
<?php ActiveForm::end(); ?>


<script type="text/javascript">
	var paramJs = (paramJs || {});
	paramJs.urlLatesJob = '<?= Yii::$app->urlManager->createAbsoluteUrl(['tr/job/budget_latesjob']); ?>';

	function lateJob() {
		var link = (link || paramJs.urlLatesJob);
		$.ajax({
			url: link,
			data: $('#job-form').serialize(),
			method: "POST",
			dataType: 'html',
			success: function(data) {
				var d = JSON.parse(data)
				$('#client_id').html(d.client_id);
				$('#job-job_code').val(d.job);
			},
		});
	}

	$('#job-form').on('beforeSubmit', function() {
		var url = '<?= Yii::$app->urlManager->createAbsoluteUrl(['tr/jobcreate/save', 'id' => $id]); ?>';
		var form_data = new FormData($('#job-form')[0]);
		return HelperSaveAjax(url, form_data);
	});
</script>

backend/modules/tr/views/jobcreate/n_code.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\JsExpression;

use kartik\widgets\ActiveForm;
use kartik\widgets\Select2;
use kartik\widgets\DatePicker;
use kartik\widgets\SwitchInput;
use yii\widgets\MaskedInput;

use common\components\JobHelper;
use common\models\hr\Employee;

JobHelper::set_title_txt($this, ['label' => Yii::t('backend', 'JOB LIST'), 'url' => ['all']], ($modelJob->isNewRecord) ? 'Create New Job' : 'Update Job  : ' . $modelJob->job_code);
echo JobHelper::widget_pjax('DetailModal');
$form = ActiveForm::begin(JobHelper::begin_form('job-form'));
echo $form->errorSummary($modelJob);
\yii\widgets\Pjax::begin(['id' => rand() . 'pjax', 'enablePushState' => false, 'id' => 'job-pjax']);
?>
<div class="alert alert-danger" id="error" style="display:none"></div>

<b>Update Job Code</b>
<div class="form-group-attached mb-3 mt-3">
	<div class="row">
		<div class="col-md-12">
			<?php
			echo $form->field($modelJob, 'job_code', ['options' => ['class' => ' form-group form-group-default']])->textInput(['class' => "form-control"]);
			// echo $form->field($modelJob, 'JobCode', ['options' => ['class' => ' form-group form-group-default']])->textInput(['class' => "form-control"]);
			?>
		</div>
	</div>
</div>

<?php
echo '<button type="button" class="btn btn-info btn-lg float-right" data-dismiss="modal">CANCEL</button>';
echo Html::submitButton('SAVE', ['class' => 'btn btn-success btn-lg float-right']);
?>

<?php \yii\widgets\Pjax::end(); ?>
<?php ActiveForm::end(); ?>


<script type="text/javascript">
	var paramJs = (paramJs || {});
	paramJs.urlLatesJob = '<?= Yii::$app->urlManager->createAbsoluteUrl(['tr/job/budget_latesjob']); ?>';

	function lateJob() {
		var link = (link || paramJs.urlLatesJob);
		$.ajax({
			url: link,
			data: $('#job-form').serialize(),
			method: "POST",
			dataType: 'html',
			success: function(data) {
				var d = JSON.parse(data)
				$('#CLientID').html(d.ClientID);
				$('#job-jobcode').val(d.job);
			},
		});
	}

	$('#job-form').on('beforeSubmit', function() {
		var url = '<?= Yii::$app->urlManager->createAbsoluteUrl(['tr/jobcreate/save', 'id' => $id]); ?>';
		var form_data = new FormData($('#job-form')[0]);
		return HelperSaveAjax(url, form_data);
	});
</script>